apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konektika-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - konektika.online
      secretName: konektika-server-tls
  rules:
    - host: konektika.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: konektika-server
                port:
                  number: 80
